### PR TITLE
Add debugging for intermittent production nil user error

### PR DESCRIPTION
**Pull request by PaulDoyle-DEFRA**
This adds debugging for an intermittent production error, which occurs during the checking of permissions for a renewing registration. It has not been possible to replicate the error in a local development environment, hence this temporary additional debugging information.
https://eaflood.atlassian.net/browse/RUBY-1921

### CODE REVIEW

**Comment by timstone** [comment]
@PaulDoyle-DEFRA if you want to deploy this code to production, do you want to turn it on and off with a feature toggle?

**Comment by timstone** [comment]
Also it might be helpful to know tier and if the registration has an account

**Review by d-a-v-e — DISMISSED** [review]

**Review by kennyevil — APPROVED** [review]

**Comment by timstone** [comment]
> @PaulDoyle-DEFRA if you want to deploy this code to production, do you want to turn it on and off with a feature toggle?

No, I don't think that's necessary. It was just an idea, if we are going to capture errrors then we should have the best available information to troubleshoot.

**Comment by PaulDoyle-DEFRA** [comment]
Replaced by https://github.com/DEFRA/waste-carriers-engine/pull/1249

**Pull request closed without merging**
